# Generated by Django 4.1.3 on 2022-11-13 17:50

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="airflow_search",
            field=models.ForeignKey(
                help_text="airflow_search",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tickets",
                to="flights.airflowsearch",
                verbose_name="airflow_search",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="currency",
            field=models.ForeignKey(
                help_text="currency",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tickets",
                to="flights.currency",
                verbose_name="currency",
            ),
        ),
    ]
