# Generated by Django 4.1.3 on 2022-11-13 20:13

from django.db import migrations


def create_own_provider(apps, schema_editor):
    Provider = apps.get_model("flights", "Provider")
    provider_a_url = "http://localhost:9000/api/v1/flights/provider-a/search/"
    provider_b_url = "http://localhost:9000/api/v1/flights/provider-b/search/"
    Provider.objects.create(title="provider_a", url=provider_a_url)
    Provider.objects.create(title="provider_b", url=provider_b_url)


def create_kzt_currency(apps, schema_editor):
    Currency = apps.get_model("flights", "Currency")
    Currency.objects.create(title="KZT", fullname="tenge", in_kzt=1)


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_alter_ticket_airflow_search_alter_ticket_currency"),
    ]

    operations = [
        migrations.RunPython(code=create_own_provider, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=create_kzt_currency, reverse_code=migrations.RunPython.noop),
    ]
